### ISSUE TITLE
github: url doesn't support slashes in commitish

### ISSUE THREAD

**Issue by ThierryGoubier** [dalehenrich/filetree#152]
the repository specification github://<user name>/<project name>[:comitish]/<path to filetree repo>'
doesn't support slashes in commitish

**Comment by dalehenrich** [comment]
Thierry,

I'm not quite sure what  problem you are reporting here ... I may be 
dense but a concrete example of a "valid commitish" that is not 
supported would keep me from splashing around ....

Dale

**Comment by krono** [comment]
I think this is related to the bug I once filed.

@ThierryGoubier, have you tried escaping (as in `/` -> `\/`) the slash in your _"commitish"_?

**Comment by ThierryGoubier** [comment]
Well, let's imagine I try to add the following tag to a branch:

a/try/of/a/silly/tag

Ok, then:

$ git tag -a a/try/of/a/silly/tag
$ git tag
a/try/of/a/silly/tag

It works. Then the github url becomes:

github://MyName/MyProject:a/try/of/a/silly/tag/repository

which makes it an interesting problem to distinguish where ends the tag and
where begins the path to the repository.

Thierry

2015-03-19 14:20 GMT+01:00 Dale Henrichs notifications@github.com:

**Comment by krono** [comment]
Hi,

On 19.03.2015, at 14:31, Thierry Goubier notifications@github.com wrote:

> Well, let's imagine I try to add the following tag to a branch:
> 
> a/try/of/a/silly/tag
> 
> Ok, then:
> 
> $ git tag -a a/try/of/a/silly/tag
> $ git tag
> a/try/of/a/silly/tag
> 
> It works. Then the github url becomes:
> 
> github://MyName/MyProject:a/try/of/a/silly/tag/repository
> 
> which makes it an interesting problem to distinguish where ends the tag and
> where begins the path to the repository.

This should Work:

github://MyName/MyProject:a\/try\/of\/a\/silly\/tag/repository

> Thierry
> 
> 2015-03-19 14:20 GMT+01:00 Dale Henrichs notifications@github.com:
> 
> > Thierry,
> > 
> > I'm not quite sure what problem you are reporting here ... I may be
> > dense but a concrete example of a "valid commitish" that is not
> > supported would keep me from splashing around ....
> > 
> > Dale
> > 
> > On 3/18/15 10:56 PM, Thierry Goubier wrote:
> > 
> > > the repository specification github:///[:comitish]/'
> > > doesn't support slashes in commitish

**Comment by ThierryGoubier** [comment]
It could work, but I have no idea who will do the unescaping for this to
work. Metacello? Is there any documentation from github on that subject?

Thierry

2015-03-19 14:29 GMT+01:00 Tobias Pape notifications@github.com:

**Comment by ThierryGoubier** [comment]
Hi,

2015-03-19 14:33 GMT+01:00 Tobias Pape notifications@github.com:

> Hi,
> 
> This should Work:
> 
> github://MyName/MyProject:a\/try\/of\/a\/silly\/tag/repository

It doesn't. In Pharo4

   MCGitHubRepository
parseLocation:
'github://MyName/MyProject:a\/try\/of\/a\/silly\/tag/repository'
version: nil

returns a repo path of 'try\/of\/a\/silly\/tag/repository' (and a project
version of 'a\') :)

ZnUrl does not understand \/ either.

Thierry

**Comment by krono** [comment]
Ok, for some reason we discussed that at dalehenrich/metacello-work#234

**Comment by ThierryGoubier** [comment]
Ok then the solution is to update Metacello, and it is not a filetree
issue. I'll close it.

Thierry

2015-03-19 14:46 GMT+01:00 Tobias Pape notifications@github.com:

**Comment by dalehenrich** [comment]
Thierry,

I am hoping that the Pharo folks will get in the habit of including the 
latest version of Metacello in their builds ...

Dale

**Comment by ThierryGoubier** [comment]
Dale,

it won't happen in Pharo 4 this time around. With more people trying githut + git with Pharo, we see more issues popping up, but it was too late inside the freeze period. Time for Pharo 5 :)

Thierry

**Comment by dalehenrich** [comment]
Yeah, with you're git support for Pharo and FileTree you've done a good 
job of making it a realistic option!

I'll keep my fingers crossed fo r5.0:)

Dale
