### ISSUE TITLE
Performance problems when opening large filetree repository in Monticello Browser

### ISSUE THREAD

**Issue by numberpi** [dalehenrich/filetree#153]
Opening a filetree repository takes ~40 seconds on my local machine (repository folder contains ~6000 files, 900 folders).

After some tallying I found the reference to #132 in MCDirectoryRepository>>cacheAllFileNamesDuring: which causes the performance issue.
While opening the repository, the filename cache is recreated over and over again, but it has to be reloaded only once in the beginning.

I would suggest something like that:

``` Smalltalk
cacheAllFileNamesDuring: aBlock 
    "https://github.com/dalehenrich/filetree/issues/132"
    | resetInternalCall |
    resetInternalCall := false.
    internalCall ifFalse: [internalCall := true.
        resetInternalCall := true.
        allFileNamesCache := nil.].

    ^ [super cacheAllFileNamesDuring: aBlock]
        ensure: [resetInternalCall ifTrue: [internalCall := false]]
```

This reduces the time to open the repo window to ~2 seconds.

**Comment by dalehenrich** [comment]
@numberpi would you mind submitting a pull request against the Squeak4.3 branch with this patch? I am  pretty busy and if you wait for me, I'll integrate this fix when I make my next (annual?) swing through Filetree:)

**Comment by numberpi** [comment]
@dalehenrich I will do it next time I get my hands on a Unix machine, because my first approach to implement it using Windows failed, cause I am unable to checkout files like "https://github.com/dalehenrich/filetree/blob/master/tests/testRepositories/ver03/Cypress-Mocks.pkg/snapshot/classes/CypressMockBasic.class/instance/name:.st" due to the colon in the filepath

**Comment by dalehenrich** [comment]
Hmmm, that is a test repository for a version of filetree/cypress that 
was not stripping illegal characters out of the file name ... so you 
could make a branch that just dropped that file on the floor ....or even 
rename the file to something different ... file names have never been 
significant to filetree/cypress ... the filenames are for humans.

Dale

**Comment by krono** [comment]
bump

**Comment by krono** [comment]
I merged the _dev into squeak4.3

Dale, how was the process to make it the default?

**Comment by dalehenrich** [comment]
Do you mean to deploy it to ss3?

**Comment by krono** [comment]
I just want people who install filetree either directly or via a metacello bootstrap to end up with the right version. Do I have to change any Baseline/Config?

**Comment by dalehenrich** [comment]
No ... FileTree is pretty much under continuous release ... once you put a change out on the platform branch, folks should pick it up the next time they load/reload, since the project refs in Baseline/Config should reference the branch itself like this:

``` Smalltalk
Metacello new
  baseline: 'FileTree';
  repository: 'github://dalehenrich/filetree:squeak4.3/repository';
  load.
```

**Comment by krono** [comment]
Good, then I'd like to consider this here deployed and good to close.
Counter arguments? :)

**Comment by dalehenrich** [comment]
nope ship it!
