### ISSUE TITLE
GitFileTree does not work anymore after Pharo 50558

### ISSUE THREAD

**Issue by marianopeck** [dalehenrich/filetree#174]
Hi @ThierryGoubier 

As for Pharo 50558 the startUpList: and shutdownList have been deprecated and now there is another way. For OSSubprocess project, I did  this workaround:

``` Smalltalk
initialize
    self initializeVMProcessInstance. 
    self flag: #removeIt.
    "This IF will be eliminated soon...only here temporary"
    (SystemVersion current highestUpdate >= 50558)
        ifTrue: [ 
            SessionManager default registerToolClassNamed: self name
             ]
        ifFalse: [ 
            Smalltalk addToStartUpList: OSSVMProcess.
            Smalltalk addToShutDownList: OSSVMProcess.
        ]
```

Could you please fix that in GitFileTree? It is failing for example with `ProcessWrapper`.

**Comment by ThierryGoubier** [comment]
I think this is an issue with ProcessWrapper.

**Comment by ThierryGoubier** [comment]
I wrote an email to Hernán for an update to ProcessWrapper

**Comment by ThierryGoubier** [comment]
Ok, and OSProcess needs that change as well.

**Comment by marianopeck** [comment]
Yes.... BTW, once we have #175 fixed , I guess I will need to merge that (pharo5.0_dev) into branch issue_171, right?

**Comment by ThierryGoubier** [comment]
This was fixed in ProcessWrapper and OSProcess
