### ISSUE TITLE
ProcessWrapper should in a separate package for windows

### ISSUE THREAD

**Issue by marianopeck** [dalehenrich/filetree#175]
Hi @ThierryGoubier 

Having to load ProcessWrapper in anything than windows is a pain. I would split at the configuration / baseline level and only load ProcessWrapper in Windows and OSProcess/OSSubprocess in Linux/OSX.

**Comment by ThierryGoubier** [comment]
Hi @marianopeck : if you have an idea for writing a configuration which allows for that, I'm interested.

So far, what I know is that you don't have the underlying OS as a platform attribute under Metacello, and that it may surprise some carrying images between OSes to see that it stops working because the support isn't installed.

I guess the best would be to add the right test when trying to run a git command and load then.

**Comment by marianopeck** [comment]
Hi @ThierryGoubier 

Yes, I know how to do that in Metacello. I will see if tomorrow I can make you a PR.
Cheers,

**Comment by marianopeck** [comment]
@ThierryGoubier Question....when I make the PR , should that have done via normal filetree + git in this case right? Because if I commit with gitfiletree I guess I will screw things up.

**Comment by ThierryGoubier** [comment]
Well, I do use gitfiletree myself, so it should be OK.

**Comment by marianopeck** [comment]
But if you use gitfiletree in a repo where gitfiletree is not used by all developers (like @dale), wouldn't you remove "metadata"? Or at least some commits would have metadata and others won't.... sounds complicated.

**Comment by ThierryGoubier** [comment]
No, if the previous ones were done by git. In short, metadata is rewritten as it is in git, and replaced by the git commit author if not.

For example, if you commit with filetree, you will have your Pharo author timestamp in the metadata. If I then update your commit and do a save with gitfiletree, your entries in the metadata with be overwritten with your git-extracted timestamp.

**Comment by marianopeck** [comment]
Hi @ThierryGoubier 

Now that I have this working, I should merge this changes into branch issue_171 and make  PR, right?

**Comment by ThierryGoubier** [comment]
Ok, I've just merged your pull request into pharo5.0_dev; so you need to update your fork of filetree, then redo a pull request. I will update the issue_171 branch as well.

**Comment by marianopeck** [comment]
Already fixed.
