### ISSUE TITLE
gitfiletree:// protocol does not work in Pharo 6

### ISSUE THREAD

**Issue by JurajKubelka** [dalehenrich/filetree#200]
When I try something like that:

```
Metacello new
    baseline: 'FileDialog';
    repository: 'gitfiletree:///home/peter/prog/file-dialog/repository';
    load.
```

It says `ZnUnknownScheme`. My scheme is `gitfiletree:///Users/jura/Documents/SourceCode/GT-Collaboration/repository/`

[stack.txt](https://github.com/dalehenrich/filetree/files/386273/stack.txt)

**Comment by JurajKubelka** [comment]
I load `FileTree` using the following script:

```
Metacello new
        baseline: 'FileTree';
        repository: 'github://dalehenrich/filetree:pharo6.0_dev/repository';
        load: 'Git'
```

**Comment by ThierryGoubier** [comment]
Hi @JurajKubelka ;

Using the same script to load GitFileTree, on Pharo6 60157, running your first Metacello script gives me the expected "directory does not exist" error.

Which version of Pharo 6 are you using? Have you updated Metacello?

Thierry

**Comment by JurajKubelka** [comment]
Hi @ThierryGoubier,

I use  60154. I will try it with 60157. What do you mean by updating Metacello? Executing the following script?:

```
Metacello new
        baseline: 'FileTree';
        repository: 'github://dalehenrich/filetree:pharo6.0_dev/repository';
        load: 'Git'
```

**Comment by ThierryGoubier** [comment]
Well you need to execute that script to get GitFileTree, so this is mandatory (and I did that as well).

I was asking if you updated something else, like Metacello itself.

Note that I didn't see any error in past versions of Pharo 6, and I know I wouldn't miss an error like yours since it would break my base image build script.

**Comment by JurajKubelka** [comment]
1. So I have fresh 60157 image. 
2. I execute

```
Metacello new
        baseline: 'FileTree';
        repository: 'github://dalehenrich/filetree:pharo6.0_dev/repository';
        load: 'Git'
```
1. I execute

```
Metacello new
    baseline: #GTCollaborate;
    repository: 'gitfiletree://', (FileLocator documents / 'SourceCode' / 'GT-Collaboration' / 'repository') asFileReference fullName;
    load.
```

and it works :-) I do not know what was wrong before.
Thanks for the discussion!
I think you can close this issue.

**Comment by ThierryGoubier** [comment]
I suspect GitFileTree wasn't loaded the first time. I'll keep your example: nice way to use FileLocator :)
