### ISSUE TITLE
Adding new gitfiletree directory in Pharo 5 does not work

### ISSUE THREAD

**Issue by JurajKubelka** [dalehenrich/filetree#202]
Steps to reproduce:
1. Open Catalog Browser,
2. Install GitFileTree,
3. Open Monticello Browser,
4. Click `+Repository` button,
5. Click `gitfiletree://` and choose a directory with your git project,
6. A debugger appears. 

Environment information:
- [stack.txt](https://github.com/dalehenrich/filetree/files/416164/stack.txt)
- Used environment: Pharo5.0, Latest update: #50699.
- Apple OS X 10.11.6

The reason is that there is no `OSSUnixSubprocess`:

```
runGitCommand: anArrayOfStrings in: aDirectory
    "..."
    Smalltalk at: #OSSUnixSubprocess ifAbsent: [  ]
    "..."
```

This is called by:

```
isGitRepository: aDirectory
    "Check that we have a git repository"

    ^ (self
        gitCommand: #('rev-parse' '--is-inside-work-tree')
        in: aDirectory) substrings first = 'true'
```

**Comment by JurajKubelka** [comment]
If I first load the following script, it works: 

```
Metacello new
    configuration: 'OSSubprocess';
    repository: 'github://marianopeck/OSSubprocess:master/repository';
    version: #stable;
    load.
```

**Comment by ThierryGoubier** [comment]
Hi @JurajKubelka , it seems to be an error within the baseline / configuration of gitfiletree in the catalog (and smalltalkhub). I'll update that.

**Comment by ThierryGoubier** [comment]
Hum, I can't see what is wrong. The baseline checks for OSProcess in the image; if not present it loads OSSubprocess. In which Pharo image were you loading it from the catalog?

**Comment by JurajKubelka** [comment]
@ThierryGoubier: I have tried it again in Pharo5.0, Latest update: #50761 and it works. Maybe some network issues were involved in the previous case. So you can likely close this issue.

**Comment by ThierryGoubier** [comment]
Ok, thanks.
